import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { activeInputs, applySwitch, planSwitch, switchTargets } from '../web/runcomfy-switch.mjs';
import { recentSwitchTargets, RECENT_SOURCES } from '../web/runcomfy-recent-switch.mjs';
import { MODELS } from '../web/runcomfy-models.mjs';

// Official schemas captured from the public ComfyUI revision recorded in this fixture.
// RunComfy definitions are generated by the real node_input_types adapter, not handwritten.
const fixture = JSON.parse(readFileSync(new URL('./fixtures/recent-switch-schemas.json', import.meta.url)));
const defs = fixture.definitions;
const typeOf = spec => Array.isArray(spec[0]) ? 'COMBO' : spec[0];
const defaultOf = spec => spec[1]?.default ?? (typeOf(spec) === 'COMFY_DYNAMICCOMBO_V3' ? spec[1].options[0].key : Array.isArray(spec[0]) ? spec[0][0] : spec[1]?.options?.[0]) ?? ({ INT: 0, FLOAT: 0, STRING: '', BOOLEAN: false }[spec[0]]);
const clone = value => JSON.parse(JSON.stringify(value));
function makeNode(type, overrides = {}) {
  const definition = defs[type], values = { ...overrides };
  for (let depth = 0; depth < 4; depth++) for (const [name, spec] of Object.entries(activeInputs(definition, values))) if (!(name in values)) values[name] = defaultOf(spec);
  const widgets = [], inputs = [];
  for (const [name, spec] of Object.entries(activeInputs(definition, values))) {
    const kind = typeOf(spec);
    if (kind === 'COMFY_AUTOGROW_V3') continue;
    if (kind !== 'COMFY_DYNAMICCOMBO_V3') inputs.push({ name, type: kind, link: null });
    if (['INT', 'FLOAT', 'STRING', 'BOOLEAN', 'COMBO', 'COMFY_DYNAMICCOMBO_V3'].includes(kind) && !spec[1]?.forceInput) widgets.push({ name, type: kind, value: values[name] });
  }
  if (Object.values(activeInputs(definition, values)).some(spec => spec[1]?.control_after_generate && !spec[1]?.forceInput)) widgets.push({ name: 'control_after_generate', value: 'fixed' });
  return { type, id: 1, widgets, inputs, outputs: definition.output.map((type, index) => ({ type, name: definition.output_name?.[index], links: [] })),
    pos: [20, 30], size: [300, 250], properties: {}, flags: {}, mode: 0,
    serialize() { return clone({ type: this.type, id: this.id, pos: this.pos, size: this.size, properties: this.properties, widgets: this.widgets, inputs: this.inputs, outputs: this.outputs }); },
    connect(slot, target, targetSlot) { return this.graph.connect(this, slot, target, targetSlot); },
  };
}
function setup(source, values = {}, media = []) {
  const node = makeNode(source, values);
  const graph = { nodes: [node], links: {}, nextId: 10, before: 0, after: 0,
    getNodeById(id) { return this.nodes.find(n => n.id === id); }, getLink(id) { return this.links[id]; },
    serialize() { return { nodes: this.nodes.map(n => n.serialize()), links: clone(this.links) }; },
    connect(origin, slot, target, targetSlot) { const id = ++this.nextId, link = { id, origin_id: origin.id, origin_slot: slot, target_id: target.id, target_slot: targetSlot }; this.links[id] = link; origin.outputs[slot].links.push(id); target.inputs[targetSlot].link = id; return link; },
    add(n) { n.graph = this; this.nodes.push(n); },
    remove(n) { this.nodes = this.nodes.filter(other => other !== n); for (const [id, link] of Object.entries(this.links)) if (link.origin_id === n.id || link.target_id === n.id) delete this.links[id]; },
    beforeChange() { this.before++; }, afterChange() { this.after++; }, change() {},
  };
  node.graph = graph;
  for (const [name, type = 'IMAGE'] of media) {
    const origin = { id: ++graph.nextId, type: 'FixtureSource', outputs: [{ type, links: [] }], serialize() { return { id: this.id, type: this.type }; }, connect: node.connect, graph };
    graph.nodes.push(origin);
    let index = node.inputs.findIndex(i => i.name === name);
    if (index < 0) { index = node.inputs.length; node.inputs.push({ name, type, link: null }); }
    graph.connect(origin, 0, node, index);
  }
  return { node, graph };
}

const positive = [
  ['OpenAIGPTImageNodeV2', 'RunComfyGPTImage25FlareT2I', { 'model.size': '1024x1024' }],
  ['OpenAIGPTImageNodeV2', 'RunComfyGPTImage25SunburstEdit', { model: 'gpt-image-2.5-sunburst', 'model.size': '2048x2048' }, [['model.images.image_1']]],
  ['OpenAIGPTImage1', 'RunComfyGPTImage2Edit', { model: 'gpt-image-2', size: '1024x1024' }, [['image']]],
  ['GeminiVideoOmniV2', 'RunComfyGeminiOmniFlashT2V', { model: 'Omni Flash', 'model.task_type': 'text_to_video' }],
  ['GeminiVideoOmniV2', 'RunComfyGeminiOmniFlashI2V', { model: 'Omni Flash', 'model.task_type': 'image_to_video' }, [['model.images.image_1']]],
  ['GeminiVideoOmniV2', 'RunComfyGeminiOmniFlashReference', { model: 'Omni Flash', 'model.task_type': 'reference_to_video' }, [['model.images.image_1']]],
  ['GeminiVideoOmniV2', 'RunComfyGeminiOmniFlashVideoEdit', { model: 'Omni Flash', 'model.task_type': 'edit' }, [['model.videos.video_1', 'VIDEO']]],
  ['HappyHorseTextToVideoApi', 'RunComfyHappyHorse11T2V'],
  ['HappyHorseImageToVideoApi', 'RunComfyHappyHorse10I2V', { model: 'happyhorse-1.0-i2v' }, [['first_frame']]],
  ['HappyHorseReferenceVideoApi', 'RunComfyHappyHorse11Reference', {}, [['model.reference_images.image1'], ['model.reference_images.image2']]],
  ['HappyHorseVideoEditApi', 'RunComfyHappyHorse10VideoEdit', {}, [['video', 'VIDEO'], ['model.reference_images.image1']]],
  ['MinimaxHailuo03TextToVideoNode', 'RunComfyMiniMaxH3T2V'],
  ['MinimaxHailuo03FirstLastFrameNode', 'RunComfyMiniMaxH3MaxI2V', { model: 'MiniMax H3 Max' }, [['first_frame'], ['last_frame']]],
  ['MinimaxHailuo03ReferenceNode', 'RunComfyMiniMaxH3Reference', {}, [['model.reference_images.image_1'], ['model.reference_videos.video_1', 'VIDEO']]],
  ['LtxApi25TextToVideo', 'RunComfyLTX25T2VFast', { 'model.duration': '6' }],
  ['LtxApi25ImageToVideo', 'RunComfyLTX25I2VPro', { model: 'LTX-2.5 (Pro)', 'model.duration': '6' }, [['image'], ['last_frame']]],
  ['LtxApi25AudioToVideo', 'RunComfyLTX25A2VFast', {}, [['audio', 'AUDIO'], ['image']]],
  ['QwenImageTextToImageApi', 'RunComfyQwenImage30ProT2I'],
  ['QwenImageTextToImageApi', 'RunComfyQwenImage21T2I'],
  ['KlingVideoNode', 'RunComfyKling30ProT2V'],
  ['KlingVideoNode', 'RunComfyKling304KI2V', {}, [['start_frame']]],
  ['KlingFirstLastFrameNode', 'RunComfyKling30ProI2V', {}, [['first_frame'], ['end_frame']]],
  ['KlingOmniProTextToVideoNode', 'RunComfyKlingO3StandardT2V'],
  ['KlingOmniProImageToVideoNode', 'RunComfyKlingO3ProReference', {}, [['reference_images']]],
  ['KlingOmniProEditVideoNode', 'RunComfyKlingO3ProV2V', {}, [['video', 'VIDEO']]],
  ['PixverseV6TextToVideoNode', 'RunComfyPixVerseV6T2V'],
  ['PixverseV6ImageToVideoNode', 'RunComfyPixVerseC1I2V', {}, [['image']]],
  ['PixverseV6FirstLastFrameNode', 'RunComfyPixVerseV6Transition', {}, [['first_frame'], ['last_frame']]],
  ['PixverseV6ExtendVideoNode', 'RunComfyPixVerseV6Extend', {}, [['video', 'VIDEO']]],
  ['RunwayAleph2VideoToVideoNode', 'RunComfyRunwayAleph2V2V', {}, [['video', 'VIDEO'], ['seed', 'INT']]],
  ['Flux3TextToVideoNode', 'RunComfyFlux3T2VDraft'],
  ['Flux3ImageToVideoNode', 'RunComfyFlux3I2V', {}, [['keyframes.image_1']]],
  ['Flux3ImageToVideoNode', 'RunComfyFlux3FirstLastFrame', { duration: '5' }, [['keyframes.image_1'], ['keyframes.image_2']]],
  ['Flux3VideoContinuationNode', 'RunComfyFlux3Extend', {}, [['video', 'VIDEO']]],
  ['ByteDance2TextToVideoNode', 'RunComfySeedance25T2V720p'],
  ['ByteDance2FirstLastFrameNode', 'RunComfySeedance25FirstLastFrame480p', {}, [['first_frame'], ['last_frame']]],
  ['ByteDance2ReferenceNodeV2', 'RunComfySeedance25Reference720p', {}, [['model.reference_images.image_1']]],
  ['ByteDance2TextToVideoNode', 'RunComfySeedance20MiniT2V', { model: 'Seedance 2.0 Mini' }],
  ['ByteDanceSeedreamNodeV3', 'RunComfySeedream50ProT2I', { model: 'seedream 5.0 pro' }],
  ['IdeogramV4', 'RunComfyIdeogram4T2I', { resolution: '2048x2048 (1:1)', rendering_speed: 'TURBO' }],
  ['ByteDanceSeedAudio', 'RunComfySeedAudio10T2A', { model: 'seed-audio-1.0', speech_rate: 25, loudness_rate: -25 }],
  ['Wan2TextToVideoApi', 'RunComfyWan27T2V'],
  ['Wan2ImageToVideoApi', 'RunComfyWan27I2V', {}, [['first_frame'], ['last_frame'], ['audio', 'AUDIO']]],
  ['Wan2ReferenceVideoApi', 'RunComfyWan27Reference', {}, [['model.reference_images.image1'], ['model.reference_videos.video1', 'VIDEO']]],
  ['Wan2VideoEditApi', 'RunComfyWan27VideoEdit', { 'model.duration': '5' }, [['video', 'VIDEO'], ['model.reference_images.image1']]],
  ['Wan3ReferenceToVideoApi', 'RunComfyWan30T2V', { 'model.duration': '5', 'model.ratio': '16:9' }, [['seed', 'INT']]],
  ['Wan3ReferenceToVideoApi', 'RunComfyWan30PrimeReference', { model: 'wan3.0-video-prime', 'model.duration': '5', 'model.ratio': '16:9' }, [['seed', 'INT'], ['model.reference_images.image1']]],
];
for (const [source, target, values = {}, media = []] of positive) test(`recent official schema preserves ${source} → ${target}`, () => {
  const { node, graph } = setup(source, values, media), before = graph.serialize();
  assert(switchTargets(node, defs).includes(target));
  const plan = planSwitch(node, target, defs);
  assert.deepEqual(plan.errors, [], plan.errors.join('\n'));
  assert.deepEqual(graph.serialize(), before, 'preview must not mutate a graph');
  assert(plan.notes.some(n => n.includes('Explicit model/settings choice')));
  const replacement = applySwitch(plan, { definitions: defs, createNode: makeNode });
  assert.equal(replacement.type, target);
  assert.equal(graph.before, 1); assert.equal(graph.after, 1);
  for (const [sourceName] of media) assert(replacement.inputs.some(i => i.name === plan.inputMap[sourceName] && i.link != null), sourceName);
});

test('every new target belongs to a family menu or an explicit no-counterpart list', () => {
  const covered = new Set(['RunComfyNanoBanana2LiteT2I', 'RunComfyNanoBanana2LiteEdit']);
  for (const type of Object.keys(RECENT_SOURCES)) {
    assert(defs[type], `Missing real schema: ${type}`);
    for (const inputs of [[], [{ name: 'image', link: 1 }, { name: 'start_frame', link: 2 }]]) for (const target of recentSwitchTargets({ type, inputs }, defs)) covered.add(target);
  }
  assert.deepEqual(Object.keys(MODELS).filter(id => !covered.has(id)).sort(), ['RunComfyACEStep15T2A', 'RunComfyACEStepAudioInpaint', 'RunComfyACEStepAudioOutpaint', 'RunComfyACEStepT2A', 'RunComfyElevenLabsMusic'].sort());
  assert(recentSwitchTargets({ type: 'OpenAIGPTImageNodeV2', inputs: [] }, defs).every(id => id.startsWith('RunComfyGPTImage')));
  assert.deepEqual(recentSwitchTargets({ type: 'ThirdPartyKlingNode', inputs: [] }, defs), []);
});

const blocked = [
  ['OpenAIGPTImageNodeV2', 'RunComfyGPTImage25FlareT2I', { model: 'gpt-image-1.5', 'model.size': '1024x1024' }, [], /no verified mapping/],
  ['OpenAIGPTImageNodeV2', 'RunComfyGPTImage25FlareT2I', {}, [], /Automatic/],
  ['OpenAIGPTImageNodeV2', 'RunComfyGPTImage25FlareEdit', { 'model.size': '1024x1024' }, [['model.images.image_1'], ['model.mask', 'MASK']], /mask/],
  ['OpenAIGPTImageNodeV2', 'RunComfyGPTImage25FlareEdit', { 'model.size': '1024x1024' }, [['model.images.image_1'], ['model.images.image_2']], /Several separate image/],
  ['OpenAIGPTImageNodeV2', 'RunComfyGPTImage25FlareT2I', { 'model.size': '1024x1024', 'model.background': 'transparent' }, [], /background/],
  ['GeminiVideoOmniV2', 'RunComfyGeminiOmniFlashT2V', { 'model.task_type': 'text_to_video' }, [], /no verified mapping/],
  ['GeminiVideoOmniV2', 'RunComfyGeminiOmniFlashI2V', { model: 'Omni Flash', 'model.task_type': 'auto' }, [['model.images.image_1']], /Auto task/],
  ['MinimaxHailuo03TextToVideoNode', 'RunComfyMiniMaxH3T2V', { model: 'MiniMax H3 Max Turbo' }, [], /no verified mapping/],
  ['LtxApi25TextToVideo', 'RunComfyLTX25T2VFast', { 'model.duration': '2' }, [], /duration/],
  ['LtxApi25TextToVideo', 'RunComfyLTX25T2VFast', { 'model.duration': '6' }, [['model.fps', 'COMBO']], /value conversion/],
  ['QwenImageEditApi', 'RunComfyQwenImage30Edit', {}, [['model.images.image_1']], /sizing/],
  ['KlingVideoNode', 'RunComfyKling30ProT2V', { multi_shot: '2 storyboards' }, [], /storyboards/],
  ['KlingVideoNode', 'RunComfyKling30ProT2V', { model: 'kling-3.0-turbo' }, [], /no verified mapping/],
  ['KlingFirstLastFrameNode', 'RunComfyKling30StandardI2V', {}, [['first_frame'], ['end_frame']], /end_frame/],
  ['KlingOmniProTextToVideoNode', 'RunComfyKlingO3ProT2V', { model_name: 'kling-video-o1' }, [], /no verified mapping/],
  ['PixverseV6FusionVideoNode', 'RunComfyPixVerseV6Reference', {}, [['subjects.subject1']], /distinct reference roles/],
  ['RunwayAleph2VideoToVideoNode', 'RunComfyRunwayAleph2V2V', {}, [['video', 'VIDEO'], ['seed', 'INT'], ['keyframes', 'RUNWAY_ALEPH2_KEYFRAME']], /structured input adapter/],
  ['Flux3ImageToVideoNode', 'RunComfyFlux3I2V', { placement: 'at times' }, [['keyframes.image_1']], /Timed keyframe/],
  ['Flux3ImageToVideoNode', 'RunComfyFlux3I2V', {}, [], /exactly 1/],
  ['Flux2ImageNode', 'RunComfyFlux2Klein4BT2I', {}, [], /different model/],
  ['IdeogramV4', 'RunComfyIdeogram4T2I', { resolution: '2048x2048 (1:1)' }, [], /rendering-speed/],
  ['ByteDanceSeedAudio', 'RunComfySeedAudio10T2A', {}, [], /no verified mapping/],
  ['ByteDanceSeedAudio', 'RunComfySeedAudio10T2A', { model: 'seed-audio-1.0', speech_rate: 200 }, [], /speed must be a finite number/],
  ['WanTextToVideoApi', 'RunComfyWan27T2V', {}, [], /no verified mapping/],
  ['Wan2VideoContinuationApi', 'RunComfyWan27I2V', {}, [['first_clip', 'VIDEO']], /continuation cannot be replaced/],
  ['Wan3ReferenceToVideoApi', 'RunComfyWan30T2V', { 'model.duration': '5', 'model.ratio': '16:9' }, [], /connection-only/],
];
for (const [source, target, values, media, message] of blocked) test(`blocks unsafe ${source} → ${target}: ${message.source}`, () => {
  const { node, graph } = setup(source, values, media), before = graph.serialize();
  assert(switchTargets(node, defs).includes(target), 'recognized unsupported source still has a visible preview');
  const plan = planSwitch(node, target, defs);
  assert(plan.errors.some(error => message.test(error)), plan.errors.join('\n'));
  assert.throws(() => applySwitch(plan, { definitions: defs, createNode: makeNode }));
  assert.deepEqual(graph.serialize(), before);
});

test('new required media groups and linked secondary outputs block before mutation', () => {
  const { node, graph } = setup('HappyHorseReferenceVideoApi');
  assert(planSwitch(node, 'RunComfyHappyHorse11Reference', defs).errors.some(e => e.includes('required reference input')));
  const { node: omni } = setup('GeminiVideoOmniV2', { model: 'Omni Flash', 'model.task_type': 'text_to_video' });
  omni.outputs[1].links = [123];
  assert(planSwitch(omni, 'RunComfyGeminiOmniFlashT2V', defs).errors.some(e => e.includes('Connected output')));
  assert.equal(graph.before, 0);
  const { node: reference } = setup('KlingOmniProImageToVideoNode');
  assert(planSwitch(reference, 'RunComfyKlingO3ProReference', defs).errors.some(e => e.includes('at least one supported media reference')));
});

test('Seed Audio rate conversions are finite, bounded FLOAT values; linked rates cannot be converted', () => {
  for (const value of [NaN, Infinity, -Infinity]) {
    const { node } = setup('ByteDanceSeedAudio', { model: 'seed-audio-1.0', speech_rate: value });
    assert(planSwitch(node, 'RunComfySeedAudio10T2A', defs).errors.some(e => e.includes('speed must be a finite number')));
  }
  const { node } = setup('ByteDanceSeedAudio', { model: 'seed-audio-1.0' }, [['speech_rate', 'INT']]);
  assert(planSwitch(node, 'RunComfySeedAudio10T2A', defs).errors.some(e => e.includes('value conversion')));
});

test('connection-only seeds preserve upstream rerun control without requiring an absent target widget', () => {
  const { node } = setup('Wan3ReferenceToVideoApi', { 'model.duration': '5', 'model.ratio': '16:9' }, [['seed', 'INT']]);
  node.widgets.find(w => w.name === 'control_after_generate').value = 'randomize';
  const plan = planSwitch(node, 'RunComfyWan30T2V', defs);
  assert.deepEqual(plan.errors, []);
  assert.equal(plan.controlAfterGenerate, undefined);
  assert(plan.notes.some(n => n.includes('upstream node controls')));
  const replacement = applySwitch(plan, { definitions: defs, createNode: makeNode });
  assert(!replacement.widgets.some(w => w.name === 'control_after_generate'));
  assert(replacement.inputs.some(i => i.name === 'seed' && i.link != null));
});

test('every family candidate can apply with its native target layout or explains its incompatibility before mutation', () => {
  const seen = new Set();
  for (const source of Object.keys(RECENT_SOURCES)) {
    const sample = positive.find(row => row[0] === source);
    const values = sample?.[2] || {}, media = sample?.[3] || [];
    const { node } = setup(source, values, media);
    for (const target of recentSwitchTargets(node, defs)) {
      const { node: freshNode, graph } = setup(source, values, media), before = graph.serialize();
      const plan = planSwitch(freshNode, target, defs);
      seen.add(target);
      if (plan.errors.length) {
        assert(plan.errors.every(message => typeof message === 'string' && message.length > 20));
        assert.throws(() => applySwitch(plan, { definitions: defs, createNode: makeNode }));
        assert.deepEqual(graph.serialize(), before);
      } else assert.equal(applySwitch(plan, { definitions: defs, createNode: makeNode }).type, target, `${source} → ${target}`);
    }
  }
  assert(seen.size >= 105, `Only ${seen.size} target variants were exercised`);
});
